[package]
name = "zed_perl"
version = "0.1.0"
edition="2021"
publish = false
license = "MIT"

[lib]
path = "src/perl.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
log = "0.4"
