id = 'perl'
name = 'Perl'
description = "Perl support"
version = '0.1.0'
schema_version = 1
authors = ["Veesh <rabbiveesh@gmail.com>"]
repository = "https://github.com/tree-sitter-perl/zed-perl"

[grammars.perl]
repository = "https://github.com/tree-sitter-perl/tree-sitter-perl"
commit = "70db420b20885ecd7268e5a710ebb3aeaef3a293"

[language_servers.perlnavigator-server]
name = "Perl Navigator"
language = "Perl"

